/**
 * Regression tests for what packaging must never ship.
 *
 * These exist because the original exclusion set was a five-item denylist
 * naming build artifacts and OS metadata, while the file collector walked
 * dotfiles. A skill folder that was also a git working tree packaged
 * `.git/config` -- which carries credentials in a token-bearing remote URL --
 * together with `.env` and `.claude/settings.local.json`. That was reproduced
 * against a real archive before the fix, not inferred.
 *
 * The failure mode is what makes it worth pinning: a denylist fails open. Every
 * secret nobody thought to name ships to whoever installs the skill, and the
 * author gets no signal it happened. A test that only checked the named
 * exclusions would have passed throughout.
 *
 * So these assert the property (nothing sensitive escapes) rather than the
 * implementation (a particular pattern is present), and they pair every
 * exclusion check with an inclusion check, because an exclusion rule that
 * swallows legitimate content is its own defect.
 */

import { test, expect } from "bun:test";
import { shouldExclude } from "../package-skill.ts";

/** Paths as they appear inside the archive: first segment is the skill folder. */
const SHIP = [
  "my-skill/SKILL.md",
  "my-skill/scripts/run.ts",
  "my-skill/scripts/lib/helper.ts",
  "my-skill/references/guide.md",
  "my-skill/assets/template.html",
  "my-skill/examples/sample.json",
  "my-skill/eval-viewer/viewer.html",
];

const NEVER_SHIP = [
  // Credential-bearing. Each of these was observed in a real archive.
  "my-skill/.env",
  "my-skill/.env.local",
  "my-skill/.git/config",
  "my-skill/.claude/settings.local.json",
  "my-skill/.npmrc",
  "my-skill/.aws/credentials",
  // Nested just as reachably as at the root.
  "my-skill/scripts/.env",
  "my-skill/references/.git/config",
  // Generated by this toolchain's own scripts, and full of model transcripts.
  "my-skill/my-skill-workspace/iteration-1/out.txt",
  "my-skill/nested/other-workspace/run.json",
  // Build and coverage output.
  "my-skill/coverage/lcov.info",
  "my-skill/dist/bundle.js",
  "my-skill/build/out.o",
  "my-skill/node_modules/pkg/index.js",
  "my-skill/__pycache__/mod.pyc",
  "my-skill/mod.pyc",
  "my-skill/.DS_Store",
  // Tests and their fixtures are dev-only.
  "my-skill/scripts/__tests__/unit.test.ts",
  "my-skill/scripts/__tests__/fixtures/golden.json",
  // Eval sets are excluded at the skill root.
  "my-skill/evals/evals.json",
];

test("ships every legitimate skill path", () => {
  for (const path of SHIP) {
    expect({ path, excluded: shouldExclude(path) }).toEqual({ path, excluded: false });
  }
});

test("never ships credentials, workspaces, build output, or tests", () => {
  for (const path of NEVER_SHIP) {
    expect({ path, excluded: shouldExclude(path) }).toEqual({ path, excluded: true });
  }
});

test("excludes any dot-prefixed entry at any depth", () => {
  // Asserted as a property rather than a list, so a secret filename nobody
  // anticipated is still caught. This is the rule that closes the original
  // hole; the named cases above only document what was actually observed.
  const invented = [
    "my-skill/.secrets",
    "my-skill/.config/token.json",
    "my-skill/deeply/nested/.hidden/key.pem",
    "my-skill/.some-tool-nobody-has-invented-yet/data",
  ];
  for (const path of invented) {
    expect({ path, excluded: shouldExclude(path) }).toEqual({ path, excluded: true });
  }
});

test("the skill folder's own name never disqualifies its contents", () => {
  // Guards the slice(1) in the matcher. A skill legitimately named to match an
  // exclusion pattern must still package: the first path segment names the
  // archive itself, so matching against it would empty the archive entirely.
  expect(shouldExclude("coverage/SKILL.md")).toBe(false);
  expect(shouldExclude("my-workspace/SKILL.md")).toBe(false);
  expect(shouldExclude("dist/scripts/run.ts")).toBe(false);
});
