/**
 * MT19937 fidelity tests against committed golden data.
 *
 * The fixtures are captured output from the CPython reference implementation
 * that `lib/mt19937.ts` replaces. They are committed as data rather than
 * regenerated by a script, so this repository needs only Bun to run its tests.
 *
 * Why this is worth testing at all: the train/test split in the description
 * optimiser seeds a generator and shuffles, and a "plausible but wrong" port is
 * indistinguishable from a correct one by eye, since both emit random-looking
 * numbers. During development a port that seeded via init_genrand instead of
 * init_by_array failed every one of these vectors while looking perfectly
 * random. That is the failure mode these fixtures exist to catch.
 *
 * Fixture shape (keys are SEEDS, not lengths):
 *   mt19937-getrandbits.json  getrandbits32_seed<N> -> uint32 sequence
 *   mt19937-shuffle.json      shuffle[<seed>]       -> list(range(len)) shuffled
 */

import { test, expect } from "bun:test";
import { PythonRandom } from "../lib/mt19937.ts";

const FIXTURES = new URL("./fixtures/", import.meta.url);

async function loadFixture(name: string): Promise<Record<string, unknown>> {
  return (await Bun.file(new URL(name, FIXTURES)).json()) as Record<string, unknown>;
}

test("reproduces getrandbits(32) sequences for every seeded fixture", async () => {
  const gold = await loadFixture("mt19937-getrandbits.json");

  let checked = 0;
  for (const [key, expected] of Object.entries(gold)) {
    const match = key.match(/^getrandbits32_seed(\d+)$/);
    if (!match || !Array.isArray(expected)) continue;

    const rng = new PythonRandom();
    rng.seed(Number(match[1]));
    const actual = (expected as number[]).map(() => Number(rng.getrandbits(32)));

    expect(actual).toEqual(expected as number[]);
    checked++;
  }

  // Guard against the fixture emptying and the test passing vacuously.
  expect(checked).toBeGreaterThan(0);
});

test("reproduces shuffle for every seeded fixture", async () => {
  const gold = await loadFixture("mt19937-shuffle.json");
  const shuffles = gold.shuffle as Record<string, number[]>;
  expect(shuffles).toBeDefined();

  let checked = 0;
  for (const [seed, expected] of Object.entries(shuffles)) {
    // The reference shuffled list(range(n)); n is recoverable from the vector.
    const rng = new PythonRandom();
    rng.seed(Number(seed));
    const actual = Array.from({ length: expected.length }, (_, i) => i);
    rng.shuffle(actual);

    expect(actual).toEqual(expected);
    checked++;
  }

  expect(checked).toBeGreaterThan(0);
});

test("split_eval_set membership and order match the reference exactly", () => {
  // Stratified by should_trigger, each stratum shuffled, then sliced. These
  // arrays came from the reference implementation for a 20-item alternating
  // set at holdout 0.4, and pin both membership and ordering.
  const set = Array.from({ length: 20 }, (_, i) => ({ id: i, should_trigger: i % 2 === 0 }));

  const rng = new PythonRandom();
  rng.seed(42);
  const trigger = set.filter((e) => e.should_trigger);
  const noTrigger = set.filter((e) => !e.should_trigger);
  rng.shuffle(trigger);
  rng.shuffle(noTrigger);

  const nTrigger = Math.max(1, Math.trunc(trigger.length * 0.4));
  const nNoTrigger = Math.max(1, Math.trunc(noTrigger.length * 0.4));

  const heldOut = [...trigger.slice(0, nTrigger), ...noTrigger.slice(0, nNoTrigger)];
  const train = [...trigger.slice(nTrigger), ...noTrigger.slice(nNoTrigger)];

  expect(train.map((e) => e.id)).toEqual([10, 12, 18, 8, 0, 2, 3, 17, 15, 1, 13, 19]);
  expect(heldOut.map((e) => e.id)).toEqual([14, 6, 4, 16, 7, 11, 5, 9]);
});

test("the shuffle floor holds: n=1 is a no-op and n=0 does not throw", () => {
  const rng = new PythonRandom();
  rng.seed(42);

  const single = [99];
  rng.shuffle(single);
  expect(single).toEqual([99]);

  const empty: number[] = [];
  rng.shuffle(empty);
  expect(empty).toEqual([]);
});
